export default [
  {
    id: 1,
    nombre: 'Collar Heart',
    modelo: 'Heart',
    categoria: 'collar',
    metal: 'oro',
    cadena: 40,
    medida: 6,
    valor: 20000,
    stock: 2,
  },
  {
    id: 2,
    nombre: 'Collar History',
    modelo: 'History',
    categoria: 'collar',
    metal: 'plata',
    cadena: 35,
    medida: 3,
    valor: 15000,
    stock: 5,
  },
  {
    id: 3,
    nombre: 'Aros Berry',
    modelo: 'Berry',
    categoria: 'aros',
    metal: 'gold',
    medida: 0.8,
    valor: 12000,
    stock: 10,
  },
  {
    id: 4,
    nombre: 'Aros Hook Blue',
    modelo: 'Hook Blue',
    categoria: 'aros',
    metal: 'gold',
    medida: 2,
    valor: 25000,
    stock: 4,
  },
  {
    id: 5,
    nombre: 'Anillo Wish',
    modelo: 'Wish',
    categoria: 'anillo',
    metal: 'plata',
    valor: 30000,
    stock: 4,
  },
  {
    id: 6,
    nombre: 'Anillo Quarzo Greece',
    modelo: 'Quarzo Greece',
    categoria: 'anillo',
    metal: 'oro',
    valor: 40000,
    stock: 2,
  },
];
