DROP TABLE IF EXISTS TRANSFERENCIAS;
DROP TABLE IF EXISTS CUENTAS;

-- Crear una tabla transferencias.
CREATE TABLE TRANSFERENCIAS (
	ID SERIAL PRIMARY KEY,
	FECHA VARCHAR(10), 
	MONTO DECIMAL,
	CUENTA_ORIGEN INT, 
	CUENTA_DESTINO INT,
	FOREIGN KEY(CUENTA_ORIGEN) REFERENCES CUENTAS(ID) ON DELETE CASCADE,
	FOREIGN KEY(CUENTA_DESTINO) REFERENCES CUENTAS(ID) ON DELETE CASCADE 
);

-- Crear una tabla cuentas.
CREATE TABLE CUENTAS(
	ID INT PRIMARY KEY, 
	SALDO DECIMAL CHECK (SALDO >= 0)
);

-- Registrar por lo menos 2 cuentas en la tabla cuentas con un saldo inicial.
INSERT INTO CUENTAS (ID, SALDO) values 
(1, 20000);
INSERT INTO CUENTAS (ID, SALDO) values 
(2, 10000);
INSERT INTO CUENTAS (ID, SALDO) VALUES 
(3, 500);

SELECT * FROM TRANSFERENCIAS;
SELECT * FROM CUENTAS;

-- TRANSACCIÓN

BEGIN;

UPDATE CUENTAS
SET SALDO = SALDO - 100
WHERE ID = 1;

UPDATE CUENTAS
SET SALDO = SALDO + 100
WHERE ID = 2;

INSERT INTO TRANSFERENCIAS (MONTO, CUENTA_ORIGEN, CUENTA_DESTINO)
VALUES (100, 1, 2);

COMMIT;

BEGIN;

UPDATE CUENTAS
SET SALDO = SALDO - 200
WHERE ID = 1;

UPDATE CUENTAS
SET SALDO = SALDO + 200
WHERE ID = 2;

INSERT INTO TRANSFERENCIAS (MONTO, CUENTA_ORIGEN, CUENTA_DESTINO)
VALUES (100, 1, 2);

COMMIT;

SELECT * FROM TRANSFERENCIAS;
SELECT * FROM CUENTAS;


BEGIN;

UPDATE CUENTAS
SET SALDO = SALDO - 200
WHERE ID = 3;

UPDATE CUENTAS
SET SALDO = SALDO + 200
WHERE ID = 2;

INSERT INTO TRANSFERENCIAS (MONTO, CUENTA_ORIGEN, CUENTA_DESTINO)
VALUES (100, 3, 2);

COMMIT;


BEGIN;

UPDATE CUENTAS
SET SALDO = SALDO - 50
WHERE ID = 3;

UPDATE CUENTAS
SET SALDO = SALDO + 50
WHERE ID = 1;

INSERT INTO TRANSFERENCIAS (MONTO, CUENTA_ORIGEN, CUENTA_DESTINO)
VALUES (100, 3, 1);

COMMIT;